package com.panostob.mycourses.ui.base.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val LightColors = lightColorScheme(
    primary = ColorPrimary,
    onPrimary = ColorPrimary,
    primaryContainer = ColorPrimary,
    onPrimaryContainer = ColorPrimary,
    secondary = ColorSecondary,
    onSecondary = ColorSecondary,
    secondaryContainer = ColorSecondary,
    onSecondaryContainer = ColorSecondary,
    tertiary = ColorTertiary,
    onTertiary = ColorTertiary,
    tertiaryContainer = ColorTertiary,
    onTertiaryContainer = ColorTertiary,
    error = Color.Red,
    errorContainer = Color.Red,
    onError = Color.Red,
    onErrorContainer = Color.Red,
    background = ColorPrimary,
    onBackground = ColorPrimary,
    surface = Color.White,
    onSurface = Color.White,
    surfaceVariant = ColorTertiary,
    onSurfaceVariant = ColorTertiary,
    outline = ColorSecondary,
    inverseOnSurface = Color.White,
    inverseSurface = Color.White,
    inversePrimary = ColorSecondary,
    surfaceTint = Color.White,
    outlineVariant = ColorSecondary,
    scrim = ColorSecondary,
)

internal val DarkColors = lightColorScheme(
    primary = ColorPrimary,
    onPrimary = ColorPrimary,
    primaryContainer = ColorPrimary,
    onPrimaryContainer = ColorPrimary,
    secondary = ColorSecondary,
    onSecondary = ColorSecondary,
    secondaryContainer = ColorSecondary,
    onSecondaryContainer = ColorSecondary,
    tertiary = ColorPrimary,
    onTertiary = ColorPrimary,
    tertiaryContainer = ColorPrimary,
    onTertiaryContainer = ColorPrimary,
    error = Color.Red,
    errorContainer = Color.Red,
    onError = Color.Red,
    onErrorContainer = Color.Red,
    background = ColorPrimary,
    onBackground = ColorPrimary,
    surface = ColorPrimary,
    onSurface = ColorPrimary,
    surfaceVariant = ColorPrimary,
    onSurfaceVariant = ColorPrimary,
    outline = ColorSecondary,
    inverseOnSurface = ColorSecondary,
    inverseSurface = ColorSecondary,
    inversePrimary = ColorSecondary,
    surfaceTint = ColorPrimary,
    outlineVariant = ColorSecondary,
    scrim = ColorSecondary,
)